import argparse

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

MIGRATED_TABLES = {
    "draft_sessions",
    "draft_picks",
    "draft_pick_events",
    "draft_recommendation_snapshots",
    "draft_targets",
}
MIGRATION_ADVISORY_LOCK = 20261010

MIGRATIONS: dict[str, tuple[str, ...]] = {
    "0001_draft_persistence": (
        """
        CREATE TABLE draft_sessions (
            id VARCHAR(36) PRIMARY KEY,
            league_key VARCHAR(80) NOT NULL REFERENCES leagues(league_key) ON DELETE CASCADE,
            season VARCHAR(9) NOT NULL,
            manager_team_key VARCHAR(100) NOT NULL REFERENCES teams(team_key) ON DELETE CASCADE,
            draft_position INTEGER NOT NULL CHECK (draft_position > 0),
            total_teams INTEGER NOT NULL CHECK (total_teams > 1),
            rounds INTEGER NOT NULL CHECK (rounds > 0),
            status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'paused', 'completed')),
            mode VARCHAR(20) NOT NULL CHECK (mode IN ('balanced', 'upside', 'safe')),
            team_slots JSONB NOT NULL,
            version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX ix_draft_sessions_league_key ON draft_sessions (league_key)",
        """
        CREATE TABLE draft_picks (
            session_id VARCHAR(36) NOT NULL REFERENCES draft_sessions(id) ON DELETE CASCADE,
            overall_pick INTEGER NOT NULL CHECK (overall_pick > 0),
            round_number INTEGER NOT NULL CHECK (round_number > 0),
            team_slot INTEGER NOT NULL CHECK (team_slot > 0),
            team_key VARCHAR(100) NOT NULL REFERENCES teams(team_key),
            selected_player_id BIGINT REFERENCES player_identity(id) ON DELETE SET NULL,
            source VARCHAR(80) NOT NULL,
            picked_at TIMESTAMPTZ,
            source_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
            PRIMARY KEY (session_id, overall_pick)
        )
        """,
        "CREATE UNIQUE INDEX uq_draft_picks_session_player ON draft_picks (session_id, selected_player_id) WHERE selected_player_id IS NOT NULL",
        """
        CREATE TABLE draft_pick_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id VARCHAR(36) NOT NULL REFERENCES draft_sessions(id) ON DELETE CASCADE,
            overall_pick INTEGER NOT NULL CHECK (overall_pick > 0),
            event_type VARCHAR(20) NOT NULL CHECK (event_type IN ('recorded', 'corrected', 'undone')),
            previous_player_id BIGINT REFERENCES player_identity(id) ON DELETE SET NULL,
            selected_player_id BIGINT REFERENCES player_identity(id) ON DELETE SET NULL,
            source VARCHAR(80) NOT NULL,
            version_after INTEGER NOT NULL CHECK (version_after > 0),
            occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            evidence JSONB NOT NULL DEFAULT '{}'::jsonb
        )
        """,
        """
        CREATE TABLE draft_recommendation_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id VARCHAR(36) NOT NULL REFERENCES draft_sessions(id) ON DELETE CASCADE,
            session_version INTEGER NOT NULL CHECK (session_version >= 0),
            recommendation_player_id BIGINT REFERENCES player_identity(id) ON DELETE SET NULL,
            input_state JSONB NOT NULL,
            response JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_draft_snapshot_version UNIQUE (session_id, session_version)
        )
        """,
        "CREATE INDEX ix_draft_snapshot_session_created ON draft_recommendation_snapshots (session_id, created_at)",
        """
        CREATE TABLE draft_targets (
            session_id VARCHAR(36) NOT NULL REFERENCES draft_sessions(id) ON DELETE CASCADE,
            player_id BIGINT NOT NULL REFERENCES player_identity(id) ON DELETE CASCADE,
            status VARCHAR(20) NOT NULL CHECK (status IN ('target', 'priority', 'watch', 'avoid')),
            note TEXT,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (session_id, player_id)
        )
        """,
        "CREATE INDEX ix_draft_targets_session_status ON draft_targets (session_id, status)",
    ),
}

DOWN_MIGRATIONS: dict[str, tuple[str, ...]] = {
    "0001_draft_persistence": (
        "DROP TABLE draft_targets",
        "DROP TABLE draft_recommendation_snapshots",
        "DROP TABLE draft_pick_events",
        "DROP TABLE draft_picks",
        "DROP TABLE draft_sessions",
    ),
}


async def upgrade(connection: AsyncConnection) -> None:
    await connection.execute(
        text("SELECT pg_advisory_xact_lock(:lock_id)"),
        {"lock_id": MIGRATION_ADVISORY_LOCK},
    )
    await connection.execute(text(
        "CREATE TABLE IF NOT EXISTS schema_migrations "
        "(revision VARCHAR(100) PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ))
    applied = set((await connection.execute(text("SELECT revision FROM schema_migrations"))).scalars())
    for revision, statements in MIGRATIONS.items():
        if revision in applied:
            continue
        for statement in statements:
            await connection.execute(text(statement))
        await connection.execute(
            text("INSERT INTO schema_migrations (revision) VALUES (:revision)"),
            {"revision": revision},
        )


async def downgrade(connection: AsyncConnection, target: str = "base") -> None:
    if target != "base" and target not in MIGRATIONS:
        raise ValueError(f"Unknown migration target: {target}")
    await connection.execute(
        text("SELECT pg_advisory_xact_lock(:lock_id)"),
        {"lock_id": MIGRATION_ADVISORY_LOCK},
    )
    await connection.execute(text(
        "CREATE TABLE IF NOT EXISTS schema_migrations "
        "(revision VARCHAR(100) PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ))
    applied = set((await connection.execute(text("SELECT revision FROM schema_migrations"))).scalars())
    for revision in reversed(tuple(MIGRATIONS)):
        if revision == target:
            break
        if revision not in applied:
            continue
        for statement in DOWN_MIGRATIONS[revision]:
            await connection.execute(text(statement))
        await connection.execute(
            text("DELETE FROM schema_migrations WHERE revision = :revision"),
            {"revision": revision},
        )


async def _main() -> None:
    from app.core.database import engine

    parser = argparse.ArgumentParser(description="Manage PostgreSQL schema migrations")
    parser.add_argument("action", choices=("upgrade", "downgrade"))
    parser.add_argument("target", nargs="?", default="base")
    args = parser.parse_args()
    async with engine.begin() as connection:
        if args.action == "upgrade":
            await upgrade(connection)
        else:
            await downgrade(connection, args.target)
    await engine.dispose()


if __name__ == "__main__":
    import asyncio

    asyncio.run(_main())